### PR TITLE
Kernel Improvements

### PR DESCRIPTION
**Pull request by codekow**
## Introduce various improvements

* fix: fstab
* add: docker container build for kernel compiling
* update: journald to avoid filling ramdisk
* add: kernel features to improve support for other uses including:
  * iscsi
  * podman / docker
  * nfs
  * mdadm
  * iptables

### CODE REVIEW

**Comment by Heisath** [comment]
Thanks for adding all this. I assume you tested the docker bits? 

Will merge this after I confirmed it builds ok.

**Comment by codekow** [comment]
@Heisath I tested with docker and podman on Fedora and Ubuntu.

Based on the way that the rootfs gets built the container would need to be privileged. There should be a way to build root without priviledged (aka buildroot project), but I didn't have time to dig into that.

**Comment by codekow** [comment]
This may also address #8

**Comment by Heisath** [comment]
How?

**Review by Heisath — APPROVED** [review]
Tested by building and booting. Looks good! Thanks for your contribution.

**Pull request merged**
